// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/Cuprumbur/weather-service/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: keyHash
func (_m *Repository) Delete(keyHash string) error {
	ret := _m.Called(keyHash)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(keyHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllApiKeys provides a mock function with given fields:
func (_m *Repository) FindAllApiKeys() ([]model.ApiKey, error) {
	ret := _m.Called()

	var r0 []model.ApiKey
	if rf, ok := ret.Get(0).(func() []model.ApiKey); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ApiKey)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindApiKey provides a mock function with given fields: keyHash
func (_m *Repository) FindApiKey(keyHash string) (model.ApiKey, error) {
	ret := _m.Called(keyHash)

	var r0 model.ApiKey
	if rf, ok := ret.Get(0).(func(string) model.ApiKey); ok {
		r0 = rf(keyHash)
	} else {
		r0 = ret.Get(0).(model.ApiKey)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(keyHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindApiKeys provides a mock function with given fields: idDetector
func (_m *Repository) FindApiKeys(idDetector int) ([]model.ApiKey, error) {
	ret := _m.Called(idDetector)

	var r0 []model.ApiKey
	if rf, ok := ret.Get(0).(func(int) []model.ApiKey); ok {
		r0 = rf(idDetector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ApiKey)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idDetector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: key
func (_m *Repository) Store(key model.ApiKey) error {
	ret := _m.Called(key)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.ApiKey) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateScopes provides a mock function with given fields: keyHash, scopes
func (_m *Repository) UpdateScopes(keyHash string, scopes []string) error {
	ret := _m.Called(keyHash, scopes)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(keyHash, scopes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
