// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/Cuprumbur/weather-service/model"
	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// CheckAccess provides a mock function with given fields: apiKey, detectorID, scope
func (_m *UseCase) CheckAccess(apiKey string, detectorID int, scope string) error {
	ret := _m.Called(apiKey, detectorID, scope)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int, string) error); ok {
		r0 = rf(apiKey, detectorID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateApiKey provides a mock function with given fields: detectorID, scopes
func (_m *UseCase) CreateApiKey(detectorID int, scopes []string) (string, error) {
	ret := _m.Called(detectorID, scopes)

	var r0 string
	if rf, ok := ret.Get(0).(func(int, []string) string); ok {
		r0 = rf(detectorID, scopes)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, []string) error); ok {
		r1 = rf(detectorID, scopes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: keyHash
func (_m *UseCase) Delete(keyHash string) error {
	ret := _m.Called(keyHash)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(keyHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllApiKeys provides a mock function with given fields:
func (_m *UseCase) FindAllApiKeys() ([]*model.ApiKey, error) {
	ret := _m.Called()

	var r0 []*model.ApiKey
	if rf, ok := ret.Get(0).(func() []*model.ApiKey); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ApiKey)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindApiKeys provides a mock function with given fields: idDetector
func (_m *UseCase) FindApiKeys(idDetector int) ([]*model.ApiKey, error) {
	ret := _m.Called(idDetector)

	var r0 []*model.ApiKey
	if rf, ok := ret.Get(0).(func(int) []*model.ApiKey); ok {
		r0 = rf(idDetector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ApiKey)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idDetector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateScopes provides a mock function with given fields: keyHash, scopes
func (_m *UseCase) UpdateScopes(keyHash string, scopes []string) error {
	ret := _m.Called(keyHash, scopes)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(keyHash, scopes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
