definitions:
  storage.Detector:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a simple weather server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /detector/{id}:
    get:
      consumes:
      - application/json
      description: get detector by id
      parameters:
      - description: name search by id
        format: int
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.Detector'
      summary: get detector by id
  /detectors:
    get:
      consumes:
      - application/json
      description: get all detectors
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/storage.Detector'
            type: array
      summary: List detectors
swagger: "2.0"
