// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/Cuprumbur/weather-service/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllDetectors provides a mock function with given fields:
func (_m *Repository) FindAllDetectors() ([]*model.Detector, error) {
	ret := _m.Called()

	var r0 []*model.Detector
	if rf, ok := ret.Get(0).(func() []*model.Detector); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Detector)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindDetector provides a mock function with given fields: id
func (_m *Repository) FindDetector(id int) (*model.Detector, error) {
	ret := _m.Called(id)

	var r0 *model.Detector
	if rf, ok := ret.Get(0).(func(int) *model.Detector); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Detector)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: d
func (_m *Repository) Store(d *model.Detector) (int64, error) {
	ret := _m.Called(d)

	var r0 int64
	if rf, ok := ret.Get(0).(func(*model.Detector) int64); ok {
		r0 = rf(d)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Detector) error); ok {
		r1 = rf(d)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: d
func (_m *Repository) Update(d *model.Detector) error {
	ret := _m.Called(d)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Detector) error); ok {
		r0 = rf(d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
